language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API=29
  - ANDROID_BUILD_TOOLS=29.0.3
android:
  components:
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
- chmod +x gradlew
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script:
- "./gradlew assembleRelease"
before_deploy:
- mv clearableedittext/build/outputs/aar/clearableedittext-release.aar clearableedittext/build/outputs/aar/clearableedittext.aar
deploy:
  provider: releases
  api_key:
    secure: kR6LUNZz4V+16ztKUroHvihfg/t7h4SEqOT2xOQnvfc2YCKKgbp9Ptfu3I6YE60I2Tu0K3Ht3O7XIeNIsYJvLmuw9bfBmLk8jT2fSLEKuxTjMOCsPKuur3hgHX0UKlfBMQNKHp74AAg4kf7CJ6NYY4s+EKgQjZphAcoMo5zYyXuNntS4hTYhk8Ts4pDvaXjb80owTtvoD8oJEni1x3jZEzT8z5n7YzgAg/BJo+thXZifSNJNH6iolKghDP4+JZCP9ot5F7v70m5JXKOeyywGxUPd16xU9Ju6rHdO21WE+W34dsKQJ4Bm5E2KVRK4W5yqArWElMq6cBuzjFy2ESJ0gX3Rsq3f0GG/9OQ+eekXvNeSt+jVmw7z6mZPTGDpVpsrFKkabhOYr7sP8HPwB0W+QbdAdUG4z2q4d9eu4Q/SYpVkpiXg2SMOlmG//8ljVZ/bM2tmWH9TSrMwG4XNXaVTNUGmIW7xStXyNV4wfOT9y81tPnPjNRsLYbOGaER/d7sEvoLUk7i9jnUzqeuWTPOz/4EKGZ/RUdZ+Vock/oSntk2kHyFC5luPPibNm+Y1J4KHut8q0l9TzKIgtNn880kOdSLzdamUKygGLNggn/gx8+zockZaHr3ikWm/ysCFWhbNnDH1BL6dkfVhOf4TT5m+a9rPKAKJJLROW9iwEPBnFBs=
  file: clearableedittext/build/outputs/aar/clearableedittext.aar
  skip_cleanup: true
  on:
    tags: true
